name: Build and deploy site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: auriga
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          FORGE_BASE_URL: ${{ github.server_url }}/migalmoreno/
        run: nix develop --command bash -c "npm install && clojure -M:build"
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CF_ACCOUNT_ID }}
        run: npx wrangler pages deploy ./site --project-name=${{ vars.CF_PAGES_PROJECT }} --branch=main
